name: bloc_firebase_auth_firestore_vgv
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.0
  cloud_firestore: ^3.5.0
  equatable: ^2.0.5
  extended_image: ^6.3.1
  firebase_auth: ^3.11.0
  firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  foundation_flutter: ^0.2.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  intl: ^0.17.0
  validators: ^3.0.0
  very_good_analysis: ^3.1.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
