// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArx9mQgZxYMpM655ZcwvqaMULylT9l6iM',
    appId: '1:818978899713:web:eca405e509096e825e7d00',
    messagingSenderId: '818978899713',
    projectId: 'bloc-fbauth-firestore-vgv',
    authDomain: 'bloc-fbauth-firestore-vgv.firebaseapp.com',
    storageBucket: 'bloc-fbauth-firestore-vgv.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWxZxfXpkMzT-zCDX0Gdt2am15tIB6e-s',
    appId: '1:818978899713:android:b64285a563e6e1a05e7d00',
    messagingSenderId: '818978899713',
    projectId: 'bloc-fbauth-firestore-vgv',
    storageBucket: 'bloc-fbauth-firestore-vgv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8zFNwDngHarBVClmueA2Aye9hHw6s0Sk',
    appId: '1:818978899713:ios:c7fc2154ce4fd7cf5e7d00',
    messagingSenderId: '818978899713',
    projectId: 'bloc-fbauth-firestore-vgv',
    storageBucket: 'bloc-fbauth-firestore-vgv.appspot.com',
    iosClientId:
        '818978899713-o8of97qan541thehoh76uke6cle7cv0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.bloc-firebase-auth-firestore-vgv',
  );
}
